# Generated by Django 5.2.6 on 2025-10-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('superuser_admin', 'Superuser Admin')], default='student', max_length=20),
        ),
    ]
