# Generated by Django 5.2.6 on 2025-10-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('superuser_admin', 'Superuser Admin')], default='student', max_length=20),
        ),
    ]
