import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file
env_path = Path(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))) / '.env'
load_dotenv(dotenv_path=env_path)

# Enable Django Sites framework for social authentication
SITE_ID = 1
# Custom user model
AUTH_USER_MODEL = 'api.CustomUser'

# Ensure media directory exists
MEDIA_ROOT_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'media')
"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^xqp!-#(@6o6a_+e7_b64+34_&+&6&8)n+2c-)d-3pvj)_w5vo'

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = False
# Check for production environment
IS_PRODUCTION = os.environ.get('DJANGO_ENV') == 'production'
# Allow localhost and 127.0.0.1 for development and testing
ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.sites',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.linkedin_oauth2',
    'api.apps.ApiConfig',  # Ensure this is the correct path to your app
]

# Grok API settings
GROK_API_KEY = os.environ.get('GROK_API_KEY')
GROK_API_ENDPOINT = os.environ.get('GROK_API_ENDPOINT', 'https://api.openai.com/v1/chat/completions')
GROK_MODEL_NAME = os.environ.get('GROK_MODEL_NAME', 'grok-1')
if GROK_API_KEY:
    os.environ['GROK_API_KEY'] = GROK_API_KEY
os.environ['DJANGO_DEBUG'] = 'True'

# dj-rest-auth and allauth settings
ACCOUNT_LOGIN_METHODS = {'username', 'email'}

# New allauth signup field configuration (replaces deprecated settings)
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']

# Session-based authentication (no JWT)
REST_USE_JWT = False

# Custom user serializer
REST_AUTH_SERIALIZERS = {
    'USER_DETAILS_SERIALIZER': 'api.serializers.UserSerializer',
}

# Social authentication providers
# Note: App credentials (client_id, secret) are stored in database via SocialApp model
# Run: python manage.py setup_google_oauth
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    },
    'linkedin_oauth2': {
        'SCOPE': ['r_liteprofile', 'r_emailaddress'],
        'PROFILE_FIELDS': ['id', 'first-name', 'last-name', 'email-address'],
    },
}

# Note: Additional allauth settings (SOCIALACCOUNT_ADAPTER, SOCIALACCOUNT_AUTO_SIGNUP, etc.) 
# are configured below with other authentication settings

# CORS settings are now defined at the bottom of this file

# CSRF settings for cookie-based auth
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:8000", 
    "http://127.0.0.1:8000",
]
CSRF_COOKIE_HTTPONLY = False  # Must be False for frontend to read CSRF token
CSRF_COOKIE_SAMESITE = 'Lax'  # Use 'Lax' for Django admin compatibility
CSRF_COOKIE_SECURE = False  # Set to True in production with HTTPS
CSRF_COOKIE_DOMAIN = None  # Don't restrict domain in development

# Session cookie settings
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'  # Use 'Lax' for cross-site request compatibility
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_COOKIE_DOMAIN = None  # Don't restrict domain in development
SESSION_COOKIE_AGE = 60 * 60 * 24 * 14  # 14 days session expiry


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Moved up before CommonMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Create media directories if they don't exist
if not os.path.exists(MEDIA_ROOT):
    os.makedirs(MEDIA_ROOT)
    os.makedirs(os.path.join(MEDIA_ROOT, 'profile_pics'))

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email settings for password reset
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'your-email@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'your-app-password')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# For development/testing, you can use the console backend
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Rest Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'api.authentication.CookieJWTAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
}

# Authentication Backends
AUTHENTICATION_BACKENDS = (
    # Django's default auth backend for username/password login
    'django.contrib.auth.backends.ModelBackend',
    # django-allauth backend for social logins and other features
    'allauth.account.auth_backends.AuthenticationBackend',
)

# Note: Google OAuth settings are now configured exclusively through
# django-allauth in the Django admin or via SocialApp model
# Run: python manage.py setup_google_oauth

# Set all-auth settings (consolidated)
ACCOUNT_EMAIL_VERIFICATION = 'optional'
# Note: ACCOUNT_USERNAME_REQUIRED and ACCOUNT_EMAIL_REQUIRED are deprecated
# They are now handled by ACCOUNT_SIGNUP_FIELDS defined above
# Removed ACCOUNT_AUTHENTICATION_METHOD - using ACCOUNT_LOGIN_METHODS instead

# Social account settings (consolidated - no duplicates)
SOCIALACCOUNT_ADAPTER = 'api.adapters.CustomSocialAccountAdapter'
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_LOGIN_ON_GET = True  # Skip intermediate auth page
SOCIALACCOUNT_QUERY_EMAIL = True   # Request email from providers

# Additional allauth settings for better OAuth flow
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'http'  # Use 'https' in production
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'  # Allow both username and email login
ACCOUNT_PRESERVE_USERNAME_CASING = False  # Usernames stored in lowercase

# Set redirect after login
LOGIN_REDIRECT_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')
# Make sure we handle port 5174 as well for development
if LOGIN_REDIRECT_URL == 'http://localhost:5173' and os.environ.get('DJANGO_ENV') != 'production':
    # Check which port is actually being used by the frontend
    import socket
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    try:
        s.bind(('localhost', 5173))
        # If we can bind to 5173, it means it's not in use, so frontend is probably on 5174
        LOGIN_REDIRECT_URL = 'http://localhost:5174'
    except:
        # Port 5173 is in use, so it's likely the frontend is using it
        pass
    finally:
        s.close()

LOGOUT_REDIRECT_URL = LOGIN_REDIRECT_URL

# Force the frontend URL to be added with google_auth_success parameter
SOCIALACCOUNT_ADAPTER = 'api.adapters.CustomSocialAccountAdapter'

# CORS Settings
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    os.environ.get('FRONTEND_URL', 'http://localhost:5173'),
    'http://localhost:5174',  # Allow port 5174 which is being used in your dev environment
    'http://127.0.0.1:5173',
    'http://127.0.0.1:5174',
]
CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
# JWT settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=3650),   # Effectively unlimited: 10 years
    'REFRESH_TOKEN_LIFETIME': timedelta(days=36500), # Effectively unlimited: 100 years
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': True,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# JWT Cookie settings for dj-rest-auth
JWT_AUTH_COOKIE = 'access_token'
JWT_AUTH_REFRESH_COOKIE = 'refresh_token'
JWT_AUTH_HTTPONLY = True
JWT_AUTH_SECURE = False  # Always False for dev, so cookies work on localhost
JWT_AUTH_SAMESITE = 'Lax'  # Lax for dev, so cookies are sent reliably
JWT_AUTH_DOMAIN = None  # None for dev, so cookies are not restricted


# Redirect users to home page after login (fixes 404 on /accounts/profile/)
LOGIN_REDIRECT_URL = 'http://localhost:5173/'

# Override settings for production
if IS_PRODUCTION:
    try:
        from .production_settings import *
        print("Loaded production settings")
    except ImportError:
        print("Production settings not found, using development settings")
